### PR TITLE
Calculate Factorial

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Issue #14 
Program to calculate factorial of numbers in Java.

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@sam0hack Kindly check :)

**Comment by sam0hack** [comment]
Please add code comments on each line and make it clear.

**Comment by shreyakapoor08** [comment]
@sam0hack Done

**Comment by sam0hack** [comment]
Great :+1:

**Comment by shreyakapoor08** [comment]
Kindly add label too

**Pull request merged**
