### PR TITLE
readme updated

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Issue #5 
I have updated the readme with all the instructions and guidelines.

Kindly review. 
Thanks :)

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@sam0hack Kindly check :)

**Comment by shreyakapoor08** [comment]
hey kindly add the "Hacktoberfest" label

**Comment by shreyakapoor08** [comment]
@sam0hack

**Comment by sam0hack** [comment]
Repo already has this label

**Pull request merged**
